import React from 'react';
import { FileText } from 'lucide-react';

export default function Terms() {
  return (
    <div className="py-24 px-6 max-w-4xl mx-auto space-y-12 min-h-screen">
      <div className="space-y-4 mt-8">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 border border-[var(--brand-cyan)]/30 bg-[var(--brand-cyan)]/5 text-[var(--brand-cyan)] font-mono text-[10px] uppercase tracking-[0.2em] mb-4">
          <FileText className="w-3 h-3" /> Contract 01.A
        </div>
        <h1 className="text-4xl md:text-5xl font-bold font-heading">Terms of Service</h1>
        <p className="text-[var(--text-secondary)] font-mono text-sm">EFFECTIVE: CURRENT</p>
      </div>

      <div className="space-y-8 text-[var(--text-secondary)] leading-relaxed">
        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-[var(--text-primary)]">1. Binding Agreement</h2>
          <p>
            By accessing Raven Adversary's public interfaces or submitting data via our terminal systems, you enter into a binding agreement structured for institutional engagement. This platform is not intended for retail utilization.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-[var(--text-primary)]">2. Information Architecture & Disclaimers</h2>
          <p>
            <strong className="text-[var(--text-primary)]">No Financial Advice:</strong> All outputs, pressure event memos, clause cards, and target structures generated by Raven Adversary constitute analytical observations derived from public data. They are expressly NOT investment, legal, or financial advice.
          </p>
          <p>
            <strong className="text-[var(--text-primary)]">No Fiduciary Duty:</strong> The use of our systems or public-facing intelligence does not establish a fiduciary relationship between Raven Adversary and the end-user.
          </p>
        </section>
        
        <section className="space-y-4 border-l-2 border-red-500/50 pl-6 py-4 px-2 bg-red-500/5">
          <h2 className="text-2xl font-bold text-[var(--text-primary)] lg:text-red-500/90">3. Prohibition on MNPI Injection</h2>
          <p className="text-[var(--text-primary)] font-medium">
            Users are strictly prohibited from transmitting Material Non-Public Information (MNPI) through the initial lead qualification tools or public chat interfaces. Any such data will be immediately quarantined and purged upon identification.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-[var(--text-primary)]">4. Advisory Engagement Priority</h2>
          <p>
            Any submission of an intelligence request or memo inquiry does not guarantee an engagement. Raven Adversary operates on strict capacity limits and prioritizes requests based on demonstrable exposure thresholds, structural complexity, and conflict-of-interest clearances.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-bold text-[var(--text-primary)]">5. Jurisdiction & Forum</h2>
          <p>
            These terms are governed by the laws of the State of Delaware. Any disputes arising from the use of the public-facing platform shall be resolved strictly within the state or federal courts located in Delaware.
          </p>
        </section>
      </div>
    </div>
  );
}
