import React from 'react';
import { Shield, CheckCircle2, AlertOctagon, HelpCircle, FileCheck, Layers, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';

export function EvidenceStandardMatrix() {
  return (
    <section className="py-24 px-6 border-t border-[var(--border-color)] bg-[var(--bg-primary)]" id="evidence-standard">
      <div className="max-w-6xl mx-auto space-y-16">
        
        {/* Section Header */}
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-[var(--border-color)] pb-8">
          <div className="max-w-3xl space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-[var(--brand-cyan)]/10 text-[var(--brand-cyan)] border border-[var(--brand-cyan)]/30 font-mono text-[9px] uppercase tracking-[0.2em] font-bold">
              <Shield className="w-3 h-3" /> EPISTEMIC DISCIPLINE // FIVE-TIER STANDARD
            </div>
            <h2 className="text-3xl md:text-5xl font-bold font-heading text-[var(--text-primary)] tracking-tight">
              The Raven Evidence Standard
            </h2>
            <p className="text-base md:text-lg text-[var(--text-secondary)] leading-relaxed">
              Every sentence generated by Raven carries an explicit epistemic weight. We enforce a strict separation between direct SEC filing extracts, mathematical derivations, structural inferences, and adversarial hypotheses.
            </p>
          </div>

          <div className="shrink-0 font-mono text-xs text-right">
            <div className="text-[var(--brand-cyan)] font-bold">// ZERO-HALLUCINATION PROTOCOL</div>
            <div className="text-[var(--text-tertiary)]">COMMIT LAYER ENFORCED</div>
          </div>
        </div>

        {/* Institutional Commitment Callout Box */}
        <div className="p-6 md:p-8 border border-[var(--brand-cyan)]/40 bg-[var(--brand-cyan)]/5 flex flex-col md:flex-row items-center gap-6 justify-between">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-none bg-[var(--brand-cyan)]/10 border border-[var(--brand-cyan)]/30 flex items-center justify-center shrink-0">
              <FileCheck className="w-6 h-6 text-[var(--brand-cyan)]" />
            </div>
            <div>
              <div className="font-mono text-xs uppercase tracking-widest text-[var(--brand-cyan)] font-bold">
                THE FOUNDATIONAL COVENANT
              </div>
              <div className="text-base md:text-lg font-bold text-[var(--text-primary)] font-heading">
                "No analytical inference is ever presented as a verified fact."
              </div>
            </div>
          </div>

          <Link
            to="/evidence-standard"
            className="px-5 py-2.5 border border-[var(--brand-cyan)] text-[var(--brand-cyan)] hover:bg-[var(--brand-cyan)] hover:text-black font-mono text-xs font-bold uppercase tracking-wider transition-colors shrink-0 flex items-center gap-2"
          >
            Review Evidence Standard <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        {/* Epistemic Tiers Grid */}
        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          
          {/* TIER 1: VERIFIED FACT */}
          <div className="p-6 border border-[var(--border-color)] bg-[var(--bg-secondary)]/20 flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[9px] font-bold text-emerald-400 uppercase tracking-widest">TIER 01</span>
                <span className="px-2 py-0.5 border border-emerald-500/30 bg-emerald-500/10 text-emerald-400 text-[8px] font-mono font-bold uppercase">
                  100% PROVENANCE
                </span>
              </div>
              <h3 className="text-xl font-bold font-heading text-[var(--text-primary)]">Verified Fact</h3>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Direct verbatim extract or exact numerical value from a primary SEC filing (10-K, 10-Q, 8-K, S-4, DEFM14A, 13D/G) with accession number and page coordinates.
              </p>
            </div>
            <div className="pt-4 border-t border-[var(--border-color)]/60 text-[9px] font-mono text-[var(--text-tertiary)]">
              EXAMPLE: ESOP share count: 414,733 shares (Schedule 13G).
            </div>
          </div>

          {/* TIER 2: DERIVED COMPUTATION */}
          <div className="p-6 border border-[var(--border-color)] bg-[var(--bg-secondary)]/20 flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[9px] font-bold text-cyan-400 uppercase tracking-widest">TIER 02</span>
                <span className="px-2 py-0.5 border border-cyan-500/30 bg-cyan-500/10 text-cyan-400 text-[8px] font-mono font-bold uppercase">
                  DETERMINISTIC
                </span>
              </div>
              <h3 className="text-xl font-bold font-heading text-[var(--text-primary)]">Derived Computation</h3>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Deterministic mathematical calculation produced by combining two or more verified public facts without subjective weighting or probabilistic assumptions.
              </p>
            </div>
            <div className="pt-4 border-t border-[var(--border-color)]/60 text-[9px] font-mono text-[var(--text-tertiary)]">
              EXAMPLE: 414,733 ESOP shares - 76,944 passed-through = 337,789 trustee vote.
            </div>
          </div>

          {/* TIER 3: STRUCTURAL INFERENCE */}
          <div className="p-6 border border-[var(--border-color)] bg-[var(--bg-secondary)]/20 flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[9px] font-bold text-purple-400 uppercase tracking-widest">TIER 03</span>
                <span className="px-2 py-0.5 border border-purple-500/30 bg-purple-500/10 text-purple-400 text-[8px] font-mono font-bold uppercase">
                  BOUNDED LOGIC
                </span>
              </div>
              <h3 className="text-xl font-bold font-heading text-[var(--text-primary)]">Structural Inference</h3>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Consequence model linking contractual covenants, regulatory thresholds, or balance sheet constraints to transaction friction under specific stress conditions.
              </p>
            </div>
            <div className="pt-4 border-t border-[var(--border-color)]/60 text-[9px] font-mono text-[var(--text-tertiary)]">
              EXAMPLE: MAE carveout forces buyer to absorb $14M credit markdown post-close.
            </div>
          </div>

          {/* TIER 4: ADVERSARIAL HYPOTHESIS */}
          <div className="p-6 border border-[var(--border-color)] bg-[var(--bg-secondary)]/20 flex flex-col justify-between space-y-6">
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <span className="font-mono text-[9px] font-bold text-amber-400 uppercase tracking-widest">TIER 04</span>
                <span className="px-2 py-0.5 border border-amber-500/30 bg-amber-500/10 text-amber-400 text-[8px] font-mono font-bold uppercase">
                  COUNTER-TACTIC
                </span>
              </div>
              <h3 className="text-xl font-bold font-heading text-[var(--text-primary)]">Adversarial Hypothesis</h3>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Stress-tested tactical scenario modeling how an hostile counterparty, activist hedge fund, or aggressive counter-bidder would exploit identified contractual fissures.
              </p>
            </div>
            <div className="pt-4 border-t border-[var(--border-color)]/60 text-[9px] font-mono text-[var(--text-tertiary)]">
              EXAMPLE: Activist leverages pass-through gap to demand board seat concessions.
            </div>
          </div>

        </div>

        {/* Claim Adjudication Status Matrix */}
        <div className="border border-[var(--border-color)] bg-[var(--bg-secondary)]/10 p-6 md:p-8 space-y-6">
          <div className="flex items-center justify-between border-b border-[var(--border-color)] pb-4">
            <div className="font-mono text-xs font-bold uppercase tracking-widest text-[var(--text-primary)]">
              CLAIM ADJUDICATION STATUS SYSTEM
            </div>
            <div className="font-mono text-[10px] text-[var(--text-tertiary)]">
              5 FORMAL SYSTEM STATES
            </div>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-4">
            <div className="p-4 border border-emerald-500/20 bg-emerald-500/5 space-y-1">
              <div className="font-mono text-xs font-bold text-emerald-400 uppercase">VERIFIED</div>
              <p className="text-[11px] text-[var(--text-secondary)] leading-relaxed">
                Confirmed by primary SEC filing citation with exact page and section.
              </p>
            </div>

            <div className="p-4 border border-red-500/20 bg-red-500/5 space-y-1">
              <div className="font-mono text-xs font-bold text-red-400 uppercase">DISPUTED</div>
              <p className="text-[11px] text-[var(--text-secondary)] leading-relaxed">
                Direct contradiction between two public disclosures or amendments.
              </p>
            </div>

            <div className="p-4 border border-amber-500/20 bg-amber-500/5 space-y-1">
              <div className="font-mono text-xs font-bold text-amber-400 uppercase">UNSUPPORTED</div>
              <p className="text-[11px] text-[var(--text-secondary)] leading-relaxed">
                Claim asserted in transaction chatter without primary filing confirmation.
              </p>
            </div>

            <div className="p-4 border border-gray-500/20 bg-gray-500/5 space-y-1">
              <div className="font-mono text-xs font-bold text-gray-400 uppercase">SUPERSEDED</div>
              <p className="text-[11px] text-[var(--text-secondary)] leading-relaxed">
                Rendered obsolete by subsequent definitive agreement amendment (S-4/A, 8-K).
              </p>
            </div>

            <div className="p-4 border border-purple-500/20 bg-purple-500/5 space-y-1">
              <div className="font-mono text-xs font-bold text-purple-400 uppercase">SPECULATIVE</div>
              <p className="text-[11px] text-[var(--text-secondary)] leading-relaxed">
                Analytical scenario modeling unpriced consequence under tail-risk events.
              </p>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
